<?php
/**
 * @author Magebit <info@magebit.com>
 * @copyright Copyright (c) Magebit, Ltd. (https://magebit.com)
 * @license https://magebit.com/code-license
 */

/** @var $block \Magento\Catalog\Block\Product\Image */
?>
<span class="product-image-container"
      style="width:<?= $block->escapeHtmlAttr($block->getWidth()) ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= ($block->getRatio() * 100) ?>%;">
        <img class="<?= $block->escapeHtmlAttr($block->getClass()) ?>"
            <?php 
                $customAttributes = $block->getCustomAttributes();
                if (is_array($customAttributes)) {
                    foreach ($customAttributes as $name => $value) {
                        echo $block->escapeHtmlAttr($name) . '="' . $block->escapeHtml($value) . '" ';
                    }
                } else {
                    echo $block->escapeHtmlAttr($customAttributes);
                }
            ?>
            src="<?= $block->escapeUrl($block->getImageUrl()) ?>"
            max-width="<?= $block->escapeHtmlAttr($block->getWidth()) ?>"
            max-height="<?= $block->escapeHtmlAttr($block->getHeight()) ?>"
            alt="<?= $block->escapeHtmlAttr($block->stripTags($block->getLabel(), null, true)) ?>"
            <?php if ($block->getData('fetchpriority') === 'high') : ?>
                fetchpriority="high"
            <?php endif; ?>/></span>
</span>
