<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<span class="product-image-container product-image-container-<?= /* @noEscape */ $block->getProductId() ?>"
      style="width:<?php /* @noEscape */ echo $block->getWidth()?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?php /* @noEscape */ echo ($block->getRatio() * 100); ?>%;">
       <img class=" <?= /* @noEscape */ $block->getClass() ?> <?php if ($block->getLazyLoad()): echo 'owl-lazy'; endif; ?>"
            <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtmlAttr($value) ?>"
            <?php endforeach; ?>
            <?php if (!$block->getLazyLoad()): ?>
                src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
            <?php endif ;?>
             width="<?php /* @noEscape */ echo $block->getWidth(); ?>"
             height="<?php /* @noEscape */ echo $block->getHeight(); ?>"
             alt="<?php /* @noEscape */ echo $block->stripTags($block->getLabel(), null, true); ?>"
            <?php if ($block->getLazyLoad()): ?>
                data-src="<?php /* @noEscape */ echo $block->getImageUrl(); ?>"
                data-src-retina="<?php /* @noEscape */ echo $block->getImageUrl(); ?>"
            <?php endif; ?>
            loading="lazy"
        /></span>
</span>
